blank_issues_enabled: false
contact_links:
  - name: ANNEX Community Discussions
    url: https://github.com/annex/annex/discussions
    about: Ask questions and discuss ideas here.
  - name: Security
    url: https://github.com/annex/annex/security/policy
    about: Report security vulnerabilities privately.
